version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: contacts-postgres-db
    restart: always
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: contacts-web-app
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=contacts_db
    depends_on:
      - db

volumes:
  postgres_data:
